### ISSUE TITLE
Can you add the center configuration for version 1.11.2?

### ISSUE THREAD

**Issue by monkey008** [samvbeckmann/ClockHUD#10]
Can you add the center configuration for version 1.11.2?

**Comment by samvbeckmann** [comment]
There's a GitHub release for that [here](https://github.com/samvbeckmann/ClockHUD/releases/tag/1.4.0-b1) you can download. I can upload it to curseforge as a 1.11 release too if you want.

**Comment by monkey008** [comment]
Thanks
This is a great mod.
