### ISSUE TITLE
Improvment: Placement of HUD

### ISSUE THREAD

**Issue by BakermanLP** [samvbeckmann/ClockHUD#7]
Hello,
I have a little improvment question to your HUD. 

Can you make a config option, that places the HUD in the top center? With different screen resolutions and scales that doesn't work for me to place it manually.

Thanks for reading this.

Michael (aka BakermanLP)

**Comment by samvbeckmann** [comment]
I've made [a new experimental 1.11 build](https://github.com/samvbeckmann/ClockHUD/releases/tag/1.4.0-b1) to this post. To activate the center behavior, set the `centeredClock` value in the config file to `true`. Can you test this version and make sure its works as you wanted?

**Comment by BakermanLP** [comment]
Works great. Just one small thing ... Can you please also make this for 1.10.2 ? Thanks a lot for your work

**Comment by BakermanLP** [comment]
As the last changes work for me, this issue can be closed
