### ISSUE TITLE
Changing License to MIT

### ISSUE THREAD

**Issue by samvbeckmann** [samvbeckmann/ClockHUD#8]
I'm looking to change the license to MIT with a 1.12 update to remove the restrictions of the GPL. In order to do this, I need permission from all contributors. So, @GirafiStudios if you have a chance, and aren't opposed to this change, if you could reply to this comment with something like "I, `github name` consent to the relicensing of my contributions to ClockHUD under the MIT license." Thanks, and sorry to bother you. I really appreciate you performing updates when I haven't had time!

**Comment by GirafiStudios** [comment]
I GirafiStudios consent to the relicensing of my contributions to ClockHUD under the MIT license.
